name: flutter_web_video_player
description: A new Flutter package.
version: 0.0.1
author: Alvaro Vasoncelos
homepage:

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
